version: 2
updates:
 - package-ecosystem: composer
   directory: "/"
   schedule:
    interval: weekly
   labels:
    - dependencies
 - package-ecosystem: docker
   directories: 
   -  "/docker/php-fpm"
   -  "/docker/laravel-horizon"
   schedule:
    interval: weekly
   labels:
    - dependencies